// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

// Types for `cohorts`
type Cohort struct {
	Cohortid         string     `json:"cohortid"`
	Name             string     `json:"name"`
	Date             *time.Time `json:"date"`
	AtSku            *int       `json:"at_sku"`
	AtID             *string    `json:"at_id"`
	Status           *string    `json:"status"`
	Zoom             *string    `json:"zoom"`
	Game             string     `json:"game"`
	Level            *int       `json:"level"`
	ImportedStudents int        `json:"imported_students"`
	StartDate        *time.Time `json:"start_date"`
	EndDate          *time.Time `json:"end_date"`
	Mapaccess        int        `json:"mapaccess"`
	Record           int        `json:"record"`
	EventID          *string    `json:"event_id"`
}

// Types for `cohort_setup_permissions`
type CohortSetupPermissions struct {
	Cohortid     string `json:"cohortid"`
	Simulationid int    `json:"simulationid"`
}

// Types for `cohortplayers`
type CohortsPlayers struct {
	Cohortplayerid string `json:"cohortplayerid"`
	Playerid       *int   `json:"playerid"`
	Cohortid       *int   `json:"cohortid"`
	Types          string `json:"types"`
}

// Type for `GameRepository`
type GameRepository struct {
	Gameid   string  `json:"gameid"`
	Token    string  `json:"token"`
	Color    string  `json:"color"`
	Gametype *string `json:"gametype"`
	Teamid   string  `json:"teamid"`
}

// Type for `games`
type Games struct {
	Gameid          string     `json:"gameid"`
	Gametype        *string    `json:"gametype"`
	Mapid           int        `json:"mapid"`
	Name            string     `json:"name"`
	Datetime        *time.Time `json:"datetime"`
	Token           string     `json:"token"`
	Rounds          int        `json:"rounds"`
	Teams           int        `json:"teams"`
	Roundlength     int        `json:"roundlength"`
	Mtime           float64    `json:"mtime"`
	Currentround    *int       `json:"currentround"`
	DistanceWeight  float64    `json:"distance_weight"`
	NumberWeight    float64    `json:"number_weight"`
	LongestWeight   float64    `json:"longest_weight"`
	LongestHqWeight float64    `json:"longest_hq_weight"`
	Multimove       int        `json:"multimove"`
	Templateid      *int       `json:"templateid"`
	Cohortid        int        `json:"cohortid"`
	Active          int        `json:"active"`
	Current         int        `json:"current"`
	Opts            *string    `json:"opts"`
	Stealcount      int        `json:"stealcount"`
	Record          int        `json:"record"`
	Ranked          int        `json:"ranked"`
}

// Type for `nots`
type Nots struct {
	Notid     string     `json:"notid"`
	Playerid  int        `json:"playerid"`
	Cohortid  int        `json:"cohortid"`
	Tag       string     `json:"tag"`
	Subtag    *string    `json:"subtag"`
	Timestamp *time.Time `json:"timestamp"`
}

// Type for `players`
type Players struct {
	Playerid       string     `json:"playerid"`
	Cohortid       string     `json:"cohortid"`
	Name           string     `json:"name"`
	Email          string     `json:"email"`
	Age            int        `json:"age"`
	Dob            *time.Time `json:"dob"`
	Username       string     `json:"username"`
	Password       *string    `json:"password"`
	Admin          int        `json:"admin"`
	Order          int        `json:"order"`
	ResetToken     string     `json:"reset_token"`
	PasswordSent   *time.Time `json:"password_sent"`
	LastLogin      time.Time  `json:"last_login"`
	Timezone       string     `json:"timezone"`
	AtID           *string    `json:"at_id"`
	HashedPassword *string    `json:"hashed_password"`
	StartDate      *time.Time `json:"start_date"`
	UserID         *string    `json:"user_id"`
}

// Type for `simulations`
type Simulations struct {
	Simulationid string `json:"simulationid"`
	Name         string `json:"name"`
	GameURL      string `json:"game_url"`
	SetupURL     string `json:"setup_url"`
	Env          string `json:"env"`
	Configvar    string `json:"configvar"`
	FieldMapping string `json:"field_mapping"`
}

// type for StarsSimulation
type StarsSimulation struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	GameURL      string `json:"gameUrl"`
	SetupURL     string `json:"setupUrl"`
	Env          string `json:"env"`
	Configvar    string `json:"configvar"`
	FieldMapping string `json:"fieldMapping"`
}

// Type for `teamplayers`
type TeamPlayers struct {
	ID       string `json:"id"`
	Teamid   string `json:"teamid"`
	Playerid string `json:"playerid"`
	Active   int    `json:"active"`
}

// Type for `teams`
type Teams struct {
	Teamid   string `json:"teamid"`
	Gameid   string `json:"gameid"`
	Color    string `json:"color"`
	Token    string `json:"token"`
	Hassteal int    `json:"hassteal"`
	Longest  int    `json:"longest"`
}
